# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160417_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='post2',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
