# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160421_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
