# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game',
        ),
    ]
